version: 2.1

orbs:
  general-platform-helpers: okta/general-platform-helpers@1.9

aliases:

  - &build_steps
    - checkout
    - run: java -version
    - run: ./mvnw clean install -Pci

jobs:

  jdk11:
    docker:
      - image: cimg/openjdk:11.0.22
    environment:
        JVM_OPTS: -Xmx3200m
    steps: *build_steps

  jdk17:
    docker:
      - image: cimg/openjdk:17.0.11
    environment:
        JVM_OPTS: -Xmx3200m
    steps: *build_steps

  jdk21:
    docker:
      - image: cimg/openjdk:21.0.2
    environment:
      JVM_OPTS: -Xmx3200m
    steps: *build_steps

  snyk-scan:
    docker:
      - image: cimg/openjdk:17.0.11
    steps:
      - checkout
      - run: ./mvnw clean install -Pci -Dmaven.test.skip.exec=true
      - general-platform-helpers/step-load-dependencies
      - general-platform-helpers/step-run-snyk-monitor:
          scan-all-projects: false
          skip-unresolved: false
          run-on-non-main: true
          additional-arguments: "--maven-aggregate-project"

workflows:
  build_and_test:
    jobs:
      - jdk11
      - jdk17
      - jdk21
  semgrep:
    jobs:
      - jdk17
      - general-platform-helpers/job-semgrep-scan:
          name: "Scan with Semgrep"
          context:
            - static-analysis
      - snyk-scan:
          name: execute-snyk
          context:
            - static-analysis
          requires:
            - jdk17
